# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' \code{LshParameterSetter}
#' 
#' Constructor: create an instance of an \code{LshParameterSetter}
#'
#' @param n  -- number of data points
#' @param d  -- dimension of the data points
#'
#'
#' \code{LshParameterSetter$params}
#' Returns a copy of the underlying parameters structure
#'
#' @seealso \code{\link{falconn/lsh_nn_table.h}}, specifically
#' \code{struct LSHConstructionParameters} for details of the returned 
#' structure.
#'
#' @return instance of \code{struct LSHConstructionParameters} representing
#'         the underlying LSH parameters
#'
#' 
#' \code{LshParameterSetter$withDefaults}
#' Sets all parameters to their default values based on data size
#'
#' @param distance -- one of the strings: "negative_inner_product", 
#'                    "euclidean_squared", or "unknown"; all other values
#'                    lead to a setting of "unknown".
#'
#' @return a reference to the original object, enabling chaining
#'
#'
#' \code{LshParameterSetter$distance}
#' Sets the distance function used in similarity search
#'
#' @param distance -- one of the strings: "negative_inner_product", 
#'                    "euclidean_squared", or "unknown"; all other values
#'                    lead to a setting of "unknown".
#'
#' @return a reference to the original object, enabling chaining
#'
#' 
#' \code{LshParameterSetter$numHashFunctions}
#' Sets the number of hash functions used in locality-sensitive hashing
#'
#' @param tables -- a positive integer, the number of hash functions
#'                  to use in locality-sensitive hashing
#'
#' @return a reference to the original object, enabling chaining
#'
#' 
#' \code{LshParameterSetter$numHashTables}
#' Sets the number of hash tables used in locality-sensitive hashing
#'
#' @param tables -- a positive integer, the number of hash tables
#'                  to use in locality-sensitive hashing
#' @return a reference to the original object, enabling chaining
#'
#' 
#' \code{LshParameterSetter$storage}
#' Sets the storage mode used in similarity search
#'
#' @param storage -- one of the strings: "flat_hash_table",
#'                   "bit_packed_flat_hash_table", "stl_hash_table",
#'                   "linear_probing_hash_table", or "unknown"; 
#'                   all other values lead to a setting of "unknown".
#'
#' @return a reference to the original object, enabling chaining
#'
#' 
#' \code{LshParameterSetter$family}
#' Sets the family used for locality-sensitive hashing
#'
#' @param family -- one of the strings: "hyperplane", "cross_polytope",
#'                  or "unknown"; all other values lead to a setting
#'                  of "unknown".
#'
#' @return a reference to the original object, enabling chaining
#'
#' 
#' \code{LshParameterSetter$rotations}
#' Sets the number of pseudo-rotations used with cross-polytope hash
#'
#' For sparse data, a value of 2 is recommended; for dense data, 1.
#' 
#' @param rotations -- number of rotations to use
#'                  or "unknown"; all other values lead to a setting
#'                  of "unknown".
#'
#' @return a reference to the original object, enabling chaining
#'
#' 
#' \code{LshParameterSetter$asList}
#' Represents parameters as an R list
#'
#' @return R-list with names corresponding to the parameters
#'
cppDoc.LshParameterSetter <- function() {
                                 "Temporary until document() handles module"
                             }


#' \code{LshNnTable}
#' 
#' Constructor: create a LSH search table for a specified data set
#'
#' Note: The FALCONN LSH nearest-neighbor search uses a static table,
#' as contructed here. To add to or change the data set, a new
#' object needs to be constructed.
#'
#' @param tDataMatrix -- the data, an R numeric matrix where
#'                       each \emph{column} is a data point.
#'                       (Thus, pass the transpose of a typical data matrix.)
#'
#' @param params -- the LSH configuration parameters
#'
#' 
#' \code{LshNnTable$dimension}
#' @return the dimension of points in the data matrix
#'
#' 
#' \code{LshNnTable$size}
#' @return the number points in the data matrix
#'
#' 
#' \code{LshNnTable$getNumProbes}
#' Returns the number of probes currently being used for multi-probe LSH
#' 
#' @return the number of probes
#'
#' 
#' \code{LshNnTable$getMaxNumCandidates}
#' Returns the maximum number of candidates considered for each search
#' 
#' @return the maximum number of candidates
#'
#' 
#' \code{LshNnTable$setNumProbes}
#' Set the number of probes used in multi-probe LSH
#' 
#' Note that this is not a costly operation and can be
#' done repeatedly once the table has been constructed.
#'
#' @param num_probes -- the number of probes to use
#'
#' @return a reference to the table object to enable chaining
#'
#' 
#' \code{LshNnTable$setMaxNumCandidates}
#' Set the maximum number of candidates to consider during similarity search
#' 
#' @param num_candidates -- the maximum number of candidates
#'
#' @return a reference to the table object to enable chaining
#' 
#' \code{LshNnTable$find_nearest_neighbor}
#' Find the data point nearest to the given query point
#'
#' Searches in the encapsulated data set with Locality-Sensitive Hashing.
#' This is an approximate nearest neighbor search.
#'
#' @param q -- query point, an R numeric vector of dimension d 
#'
#' @return index of the data point nearest to \code{q}, wrapped in
#'         an R integer vector
#'
#' 
#' \code{LshNnTable$find_k_nearest_neighbors}
#' Find the data points nearest to the given query point
#'
#' Searches in the encapsulated data set with Locality-Sensitive Hashing.
#' This is an approximate nearest neighbor search.
#'
#' @param q -- query point, an R numeric vector of dimension d 
#' 
#' @param k -- the number of nearest neighbors to return
#'
#' @return vector of indicies of the data points nearest to \code{q},
#'         wrapped in an R integer vector
#'
#' 
#' \code{LshNnTable$find_near_neighbors}
#' Find the data points within a specified radius of the given query point
#'
#' Searches in the encapsulated data set with Locality-Sensitive Hashing.
#' This is an approximate nearest neighbor search.
#'
#' @param q -- query point, an R numeric vector of dimension d 
#' 
#' @param radius -- radius around the query point in which to search
#'
#' @return vector of indicies of the data points within radius of \code{q},
#'         wrapped in an R integer vector
#'
#' 
#' \code{LshNnTable$get_candidates}
#' Find all data points found in a single probing sequence
#'
#' This is a low-level operation. Note that a single data point might
#' appear multiple times in the result if several hash tables are used.
#' These duplicates are included in the returned value.
#'
#' @param q -- query point, an R numeric vector of dimension d 
#' 
#' @return vector of indicies of the data points found in the search,
#'         which may include duplicates, wrapped in an R integer vector
#'
#' 
#' \code{LshNnTable$get_unique_candidates}
#' Find all data points found in a single probing sequence, duplicates removed
#'
#' This is a low-level operation. Note that a single data point might
#' appear multiple times in the result if several hash tables are used.
#' These duplicates are removed from the returned value.
#'
#' @param q -- query point, an R numeric vector of dimension d 
#' 
#' @return vector of indicies of the data points found in the search,
#'         which will not include duplicates, wrapped in an R integer vector
#'
#' 
#' \code{LshNnTable$guneNumProbes}
#' Find number of probes to achieve target precision on training data
#'
#' During the search for the optimal number of probes, this changes
#' the set number of probes via \code{setNumProbes()}. However, the
#' number originally set on entry is restored on exit.
#'
#' @param queries          -- matrix of query points, one point per
#'                            \emph{column} (pass transpose if necessary)
#' @param answers          -- vector of indices into data table representing
#'                            the nearest neighbor to the corresponding query
#' @param target_precision -- minimal correctness probability to achieve
#' @param init_num_probes  -- number of probes at which to start search
#' @param max_iterations   -- maximum number of iterations to consider;
#'                            default of -1 means no limit
#'                            
#' @return number of probes to use to achieve
#'
cppDoc.LshNnTable <- function() {
                         "Temporary until document() handles module"
                     }
